FROM node:18-alpine

WORKDIR /app

# Installation des dépendances globales
RUN npm install -g typescript ts-node

# Copie des fichiers de configuration
COPY package*.json ./
COPY tsconfig.json ./

# Installation des dépendances du projet
RUN npm install

# Installer PostgreSQL client pour utiliser pg_isready
RUN apk add --no-cache bash postgresql-client

# Script d'attente
COPY scripts/wait-for-seed.sh /app/wait-for-seed.sh

# Copie du code source
COPY . .

# Création du dossier dist
RUN mkdir -p dist

# Ajouter les permissions pour le script
RUN chmod +x /app/wait-for-seed.sh

EXPOSE 4000

ENTRYPOINT ["/app/wait-for-seed.sh"]
CMD ["npm", "start"]