-- Insertion des tags
INSERT INTO tags (name, description) VALUES
('Pro', 'Produits destinés aux professionnels'),
('Gaming', 'Produits optimisés pour le jeu'),
('Haute Performance', 'Produits avec des performances supérieures'),
('Compact', 'Produits de petite taille ou ultraportables'),
('5G', 'Compatible avec les réseaux 5G'),
('WiFi 6', 'Compatible avec le standard WiFi 6'),
('Apple', 'Produits de la marque Apple'),
('Windows', 'Produits fonctionnant sous Windows'),
('Android', 'Produits fonctionnant sous Android'),
('Économie d''énergie', 'Produits à faible consommation énergétique'),
('Reconditionné', 'Produits remis à neuf'),
('Stock limité', 'Produits en quantité limitée'),
('Dernière génération', 'Produits de la dernière génération'),
('USB-C', 'Équipé de ports USB-C'),
('RAY TRACING', 'Compatible avec la technologie Ray Tracing'),
('SSD', 'Équipé d''un disque SSD'),
('4K', 'Compatible avec la résolution 4K'),
('Bluetooth 5.0', 'Compatible Bluetooth 5.0'),
('AI Ready', 'Compatible avec les fonctionnalités d''IA'),
('HDR', 'Compatible avec la technologie HDR'),
('Éco-responsable', 'Produits respectueux de l''environnement ou fabriqués avec des matériaux durables'),
('Nouveauté', 'Nouveaux produits ajoutés au catalogue'),
('Promotion', 'Produits actuellement en promotion'),
('Best-seller', 'Produits les plus vendus'),
('Made in France', 'Produits fabriqués en France'),
('Artisanal', 'Produits fabriqués à la main ou de manière artisanale'),
('Sur mesure', 'Produits personnalisables ou sur mesure'),
('Premium', 'Produits haut de gamme'),
('Exclusif', 'Produits en exclusivité'),
('Liquidation', 'Produits en fin de série'),
('Eco-conçu', 'Produits conçus selon des principes écologiques'),
('Connecté', 'Produits avec fonctionnalités connectées'),
('Design', 'Produits au design remarquable'),
('Certifié', 'Produits avec certification qualité')
ON CONFLICT (name) DO NOTHING;